image: registry.meia8.com/john/node:8.7.0

stages:
- build
- deploy

variables:
  CONTAINER_REGISTRY: registry.meia8.com
  CONTAINER_RELEASE_IMAGE_RELEASE: $CONTAINER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:release
  CONTAINER_RELEASE_IMAGE_TESTER: $CONTAINER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:tester
  CONTAINER_RELEASE_IMAGE: $CONTAINER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest
  CONTAINER_RELEASE_IMAGE_TAG: $CONTAINER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_TAG
build-tags:
  stage: build
  script:
    - cnpm install
    - npm run build
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CONTAINER_REGISTRY
    - docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker tag $CONTAINER_RELEASE_IMAGE $CONTAINER_RELEASE_IMAGE_TAG
    - docker push $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE_TAG
  only:
  - tags
deploy-master:
  stage: deploy
  script:
    - cnpm install
    - npm run build
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CONTAINER_REGISTRY
    - docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE
    - kubectl delete -f deployment.yaml
    - kubectl create -f deployment.yaml
  environment:
    name: staging
    url: https://b-dev.qms888.com/qms-b/
  only:
  - master
  
