const tool = require('./index.js');
// console.log(tool.uuid())
// console.log(tool.uuid(6, 18))
// console.log(tool.getStr(123))
// console.log(tool.getStr({name: "Jack", age: 32}))
// console.log(tool.getStr("[9,1,1]"))
// console.log(tool.getParse({name: "Jack", age: 32}))
// console.log(tool.getParse([1,3,6]))
// console.log(tool.getParse('abc'))
// console.log(tool.ck.Object({ name: 'marry' }))
// console.log(tool.ck.Object(123))
// console.log(tool.ck.Boolean(false))
console.log(tool.ck.Number('123'))
console.log(tool.ck.String('123'))
console.log(tool.ck.Empty({}))
console.log(tool.ck.Empty({ name: 'jack' }))
console.log(tool.ck.Empty([]))
console.log(tool.ck.Empty(123))
console.log(tool.ck.Empty(0))
console.log(tool.ormErr(null))
console.log(tool.ormErr(undefined))
console.log(tool.ormErr(123))
